### ISSUE TITLE
Can we apply "net effect" to other outlier detection algorithms (e.g., density-based outlier detection)?

### ISSUE THREAD

**Issue by lteyoungjun** [kaist-dmlab/NETS#1]
Can we apply "net effect" to other outlier detection algorithms (e.g. density-based outlier detection)?

**Comment by cliveyn** [comment]
Sure. Please refer to [STARE](https://github.com/kaist-dmlab/STARE) where "net effect" is used when updating the weights of kernel centers for estimating densities.
